/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class menu_utama extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    private data_kategori data_kategori;
    private data_barang data_barang;
    private data_supplier data_supplier;
    private data_gudang data_gudang;
    private transaksi_bm transaksi_bm;
    private transaksi_bk transaksi_bk;
    
    
    private void initForm() {
        data_kategori = new data_kategori();
        data_barang = new data_barang(); 
        data_supplier = new data_supplier();
        data_gudang = new data_gudang();
        transaksi_bm = new transaksi_bm();
        transaksi_bk = new transaksi_bk();
    }
    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnCetakBarang = new javax.swing.JButton();
        btnCetakMasuk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuKategori = new javax.swing.JMenuItem();
        menuBarang = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenuItem();
        menuGudang = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuBM = new javax.swing.JMenuItem();
        menuBK = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuReportBM = new javax.swing.JMenuItem();
        menuReportBK = new javax.swing.JMenuItem();
        menuReportBarang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        btnCetakBarang.setText("CETAK LAPORAN BARANG");
        btnCetakBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakBarangActionPerformed(evt);
            }
        });

        btnCetakMasuk.setText("CETAK LAPORAN BARANG MASUK");
        btnCetakMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakMasukActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jButton1.setText("CETAK LAPORAN BARANG KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnCetakBarang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCetakMasuk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCetakBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetakMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(960, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnCetakBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCetakMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jMenu1.setText("User");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        menuKategori.setText("Data Kategori");
        menuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKategoriActionPerformed(evt);
            }
        });
        jMenu2.add(menuKategori);

        menuBarang.setText("Data Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        jMenu2.add(menuBarang);

        menuSupplier.setText("Data Supplier");
        menuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(menuSupplier);

        menuGudang.setText("Data Gudang");
        menuGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGudangActionPerformed(evt);
            }
        });
        jMenu2.add(menuGudang);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        menuBM.setText("Transaksi Barang Masuk");
        menuBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBMActionPerformed(evt);
            }
        });
        jMenu3.add(menuBM);

        menuBK.setText("Transaksi Barang Keluar");
        menuBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBKActionPerformed(evt);
            }
        });
        jMenu3.add(menuBK);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        menuReportBM.setText("Laporan Transaksi Masuk");
        jMenu4.add(menuReportBM);

        menuReportBK.setText("Laporan Transaksi Keluar");
        jMenu4.add(menuReportBK);

        menuReportBarang.setText("Laporan Barang");
        menuReportBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportBarangActionPerformed(evt);
            }
        });
        jMenu4.add(menuReportBarang);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKategoriActionPerformed
        if (!data_kategori.isVisible()) {
            jDesktopPane1.add(data_kategori);
            data_kategori.show();
        }
    }//GEN-LAST:event_menuKategoriActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
       if (!data_barang.isVisible()) {
           jDesktopPane1.add(data_barang);
           data_barang.show();
       }
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupplierActionPerformed
        if (!data_supplier.isVisible()) {
            jDesktopPane1.add(data_supplier);
            data_supplier.show();
        }
    }//GEN-LAST:event_menuSupplierActionPerformed

    private void menuGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGudangActionPerformed
        if (!data_gudang.isVisible()) {
            jDesktopPane1.add(data_gudang);
            data_gudang.show();
        }
    }//GEN-LAST:event_menuGudangActionPerformed

    private void menuBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBMActionPerformed
        if (!transaksi_bm.isVisible()) {
            jDesktopPane1.add(transaksi_bm);
            transaksi_bm.show();
        }
    }//GEN-LAST:event_menuBMActionPerformed

    private void menuBKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBKActionPerformed
         if (!transaksi_bk.isVisible()) {
            jDesktopPane1.add(transaksi_bk);
            transaksi_bk.show();
        }
    }//GEN-LAST:event_menuBKActionPerformed

    private void menuReportBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportBarangActionPerformed
         
    }//GEN-LAST:event_menuReportBarangActionPerformed

    private void btnCetakBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakBarangActionPerformed
          try {
              
              JasperDesign jasdi = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\App Inventaris\\src\\laporan\\reportBarang.jrxml");
              String sql = "select * from tb_barang order by kode_part asc";
              JRDesignQuery newQuery = new JRDesignQuery();
              newQuery.setText(sql);
              jasdi.setQuery(newQuery);
              JasperReport js = JasperCompileManager.compileReport(jasdi);
              JasperPrint jp = JasperFillManager.fillReport(js, null,conn);
              JasperViewer.viewReport(jp);
          }  catch (Exception e){
              JOptionPane.showConfirmDialog(rootPane, e);
          }
    }//GEN-LAST:event_btnCetakBarangActionPerformed

    private void btnCetakMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakMasukActionPerformed
       try {
              
              JasperDesign jasdi2 = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\App Inventaris\\src\\laporan\\reportBm.jrxml");
              String sql = "select * from tb_brg_masuk order by id_bm asc";
              JRDesignQuery newQuery = new JRDesignQuery();
              newQuery.setText(sql);
              jasdi2.setQuery(newQuery);
              JasperReport js = JasperCompileManager.compileReport(jasdi2);
              JasperPrint jp = JasperFillManager.fillReport(js, null,conn);
              JasperViewer.viewReport(jp);
          }  catch (Exception e){
              JOptionPane.showConfirmDialog(rootPane, e);
          }
    }//GEN-LAST:event_btnCetakMasukActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
              
              JasperDesign jasdi3 = JRXmlLoader.load("C:\\Users\\USER\\Documents\\NetBeansProjects\\App Inventaris\\src\\laporan\\reportBk.jrxml");
              String sql = "select * from tb_brg_keluar order by id_bk asc";
              JRDesignQuery newQuery = new JRDesignQuery();
              newQuery.setText(sql);
              jasdi3.setQuery(newQuery);
              JasperReport js = JasperCompileManager.compileReport(jasdi3);
              JasperPrint jp = JasperFillManager.fillReport(js, null,conn);
              JasperViewer.viewReport(jp);
          }  catch (Exception e){
              JOptionPane.showConfirmDialog(rootPane, e);
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakBarang;
    private javax.swing.JButton btnCetakMasuk;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBK;
    private javax.swing.JMenuItem menuBM;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuGudang;
    private javax.swing.JMenuItem menuKategori;
    private javax.swing.JMenuItem menuReportBK;
    private javax.swing.JMenuItem menuReportBM;
    private javax.swing.JMenuItem menuReportBarang;
    private javax.swing.JMenuItem menuSupplier;
    // End of variables declaration//GEN-END:variables
}
